name: Terraform CI

on:
  pull_request:
  push:
    branches:
      - develop
      - staging 
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Format Check
        run:  terraform fmt -check -recursive terraform/

      - name: Terraform Init
        working-directory:  terraform/environments/dev
        run:  terraform init -backend=false

      - name: Terraform Validate
        working-directory:  terraform/environments/dev
        run:  terraform validate
      
      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan